Applied coding style (shfmt) and static analysis (shellcheck) to shell scripts.

diff --git a/helpers/add-pkg b/helpers/add-pkg
--- a/helpers/add-pkg
+++ b/helpers/add-pkg
@@ -1,9 +1,18 @@
 #!/bin/sh
+#
+# This is an OS-agnostic helper to install package(s).
+#
 
 set -e # Exit immediately if a command exits with a non-zero status.
 
 usage() {
-    echo "usage: $(basename "$0") [--virtual NAME ] PKG [PKG...]"
+    echo "usage: $(basename "$0") [--virtual NAME ] PKG [PKG...]" >&2
+    exit 1
+}
+
+die() {
+    echo "ERROR: $*" >&2
+    exit 1
 }
 
 trap : TERM QUIT INT
@@ -21,12 +30,11 @@ install_pkg_alpine() {
     VIRTUAL_PKG="$1"
     shift
 
-    APK_EXTRA_OPTS=
-    if [ "$VIRTUAL_PKG" -eq 1 ]; then
-        APK_EXTRA_OPTS="--virtual"
+    if [ "${VIRTUAL_PKG}" -eq 1 ]; then
+        set -- "--virtual" "$@"
     fi
 
-    apk --no-cache add $APK_EXTRA_OPTS "$@"
+    apk --no-cache add "$@"
 }
 
 cleanup_alpine() {
@@ -45,16 +53,15 @@ install_pkg_debian() {
     VIRTUAL_PKG="$1"
     shift
 
-    if [ "$VIRTUAL_PKG" -eq 1 ]; then
+    if [ "${VIRTUAL_PKG}" -eq 1 ]; then
         VIRTUAL_PKG_NAME=$1
         shift
 
-        if [ -f /var/lib/apt/$VIRTUAL_PKG_NAME.virtual ]; then
-            echo "ERROR: Virtual package '$VIRTUAL_PKG_NAME' already exists."
-            exit 1
+        if [ -f "/var/lib/apt/${VIRTUAL_PKG_NAME}.virtual" ]; then
+            die "Virtual package '${VIRTUAL_PKG_NAME}' already exists."
         fi
 
-        echo "$*" > /var/lib/apt/$VIRTUAL_PKG_NAME.virtual
+        echo "$*" > "/var/lib/apt/${VIRTUAL_PKG_NAME}.virtual"
     fi
 
     if [ -n "$1" ]; then
@@ -66,9 +73,9 @@ install_pkg_debian() {
 cleanup_debian() {
     apt-get -q clean
     rm -rf /var/lib/apt/lists/* \
-           /var/log/dpkg.log \
-           /var/log/alternatives.log \
-           /var/log/apt/*
+        /var/log/dpkg.log \
+        /var/log/alternatives.log \
+        /var/log/apt/*
 }
 
 #
@@ -76,7 +83,7 @@ cleanup_debian() {
 #
 
 is_pkg_installed() {
-    if [ -n "$(which apk)" ]; then
+    if command -v apk > /dev/null; then
         is_pkg_installed_alpine "$@"
     else
         is_pkg_installed_debian "$@"
@@ -84,7 +91,7 @@ is_pkg_installed() {
 }
 
 install_pkg() {
-    if [ -n "$(which apk)" ]; then
+    if command -v apk > /dev/null; then
         install_pkg_alpine "$@"
     else
         install_pkg_debian "$@"
@@ -92,7 +99,7 @@ install_pkg() {
 }
 
 cleanup() {
-    if [ -n "$(which apk)" ]; then
+    if command -v apk > /dev/null; then
         cleanup_alpine
     else
         cleanup_debian
@@ -105,10 +112,9 @@ cleanup() {
 
 if [ -z "$1" ]; then
     usage
-    exit 1
 fi
 
-if [ -z "$(which apk)" ]; then
+if command -v apk > /dev/null; then
     export DEBIAN_FRONTEND=noninteractive
 fi
 
@@ -118,21 +124,22 @@ if [ "$1" = "--virtual" ]; then
     if [ -z "$1" ]; then
         echo "Virtual package name missing."
         usage
-        exit 1
     fi
     VIRTUAL_PKG="$1"
     shift
 fi
 
-if [ -n "$VIRTUAL_PKG" ]; then
-    PKGS="$VIRTUAL_PKG"
-    for PKG in "$@"
-    do
-        if ! is_pkg_installed $PKG; then
-            PKGS="$PKGS $PKG"
+if [ -n "${VIRTUAL_PKG}" ]; then
+    pkgs="${VIRTUAL_PKG}"
+    for pkg in "$@"; do
+        if ! is_pkg_installed "${pkg}"; then
+            pkgs="${pkgs} ${pkg}"
         fi
     done
-    install_pkg 1 $PKGS
+    # shellcheck disable=2086
+    install_pkg 1 ${pkgs}
 else
     install_pkg 0 "$@"
 fi
+
+# vim:ft=sh:ts=4:sw=4:et:sts=4
diff --git a/helpers/is-bool-val-true b/helpers/is-bool-val-true
--- a/helpers/is-bool-val-true
+++ b/helpers/is-bool-val-true
@@ -4,34 +4,34 @@ set -e # Exit immediately if a command exits with a non-zero status.
 set -u # Treat unset variables as an error.
 
 usage() {
-    >&2 echo "usage: $(basename "$0") VALUE
+    if [ -n "${1:-}" ]; then
+        echo "ERROR: $*" >&2
+        echo "" >&2
+    fi
+
+    echo "usage: $(basename "$0") VALUE
 
 Determine if a boolean value is true.
 
 Arguments:
 
-  VALUE      Boolean value.
-"
+    VALUE      Boolean value.
+" >&2
+    exit 2
 }
 
 ENV_VAL="${1:-}"
 
-if [ "$ENV_VAL" = "-h" ] || [ "$ENV_VAL" = "--help" ]
-then
+if [ "${ENV_VAL}" = "-h" ] || [ "${ENV_VAL}" = "--help" ]; then
     usage
-    exit 2
 fi
 
-if [ -z "$ENV_VAL" ]
-then
-    >&2 echo "ERROR: Boolean value missing."
-    >&2 echo ""
-    usage
-    exit 2
+if [ -z "${ENV_VAL}" ]; then
+    usage "Boolean value missing."
 fi
 
-case "$(echo $ENV_VAL | tr '[:upper:]' '[:lower:]')" in
-    1|true|yes|y|enabled|enable|on) exit 0 ;;
+case "$(echo "${ENV_VAL}" | tr '[:upper:]' '[:lower:]')" in
+    1 | true | yes | y | enabled | enable | on) exit 0 ;;
     *) exit 1 ;;
 esac
 
diff --git a/helpers/sed-patch b/helpers/sed-patch
--- a/helpers/sed-patch
+++ b/helpers/sed-patch
@@ -1,45 +1,72 @@
 #!/bin/sh
+#
+# Wrapper for sed with a patch-like behavior.
+#
+# The wrapper returns:
+#   - A success when running the sed expression results in changes applied to
+#     to file.
+#   - An error when running the sed expression results in no changes applied to
+#     the file.
+#
+# NOTE: sed option '-i' is already supplied by this script.
+#
 
 usage() {
+    if [ -n "${1:-}" ]; then
+        echo "ERROR: $*" >&2
+        echo "" >&2
+    fi
+
     echo "usage: $(basename "$0") [SED_OPT...] SED_EXPRESSION FILE
 
 sed with a patch-like behavior.
 
-This helper returns:
-  - A success when running the sed expression SED_EXPRESSION results in changes
-    applied to file FILE.
-  - An error when running the sed expression SED_EXPRESSION results in no change
-    to file FILE.
-
 NOTE: sed option '-i' is already supplied by this script.
-"
+" >&2
+    exit 1
 }
 
-eval FILE=\${$#}
+die() {
+    echo "ERROR: $*" >&2
+    exit 1
+}
+
+cleanup() {
+    [ ! -f "${fpath}".bak ] || rm -f "${fpath}".bak
+}
+
+trap : TERM QUIT INT
+trap "cleanup" EXIT
+
+fpath=
+eval fpath="\${$#}"
 
 if [ "$#" -lt 2 ]; then
-    echo "ERROR: Not enough arguments."
-    exit 1
+    usage " Not enough arguments."
+else
+    for arg in "$@"; do
+        if [ "${arg}" = "-i" ]; then
+            echo "ERROR: The '-i' option should not be specified." >&2
+            exit 1
+        fi
+    done
 fi
 
 sed -i.bak "$@"
-RC="$?"
-if [ "$RC" -eq 0 ]; then
-    diff "$FILE" "$FILE".bak > /dev/null 2>&1
+rc="$?"
+if [ "${rc}" -eq 0 ]; then
+    diff "${fpath}" "${fpath}".bak > /dev/null 2>&1
     case $? in
         0)
             # Files are the same.
-            echo "ERROR: No modification applied to $FILE."
-            RC=1
+            die "No modification applied to ${fpath}."
             ;;
         1)
-            # Files differ.
-            RC=0
+            # Files differ, OK.
+            exit 0
             ;;
-        *)
-            ;;
+        *) ;;
     esac
 fi
 
-rm -f "$FILE".bak
-exit $RC
+# vim:ft=sh:ts=4:sw=4:et:sts=4
diff --git a/helpers/set-cont-env b/helpers/set-cont-env
--- a/helpers/set-cont-env
+++ b/helpers/set-cont-env
@@ -1,23 +1,37 @@
 #!/bin/sh
+#
+# Add/set an environment variable to /etc/cont-env.d.
+#
 
 set -e # Exit immediately if a command exits with a non-zero status.
 set -u # Treat unset variables as an error.
 
 usage() {
+    if [ -n "${1:-}" ]; then
+        echo "ERROR: $*" >&2
+        echo "" >&2
+    fi
+
     echo "usage: $(basename "$0") NAME [VALUE]
 
 Save a container environment variable.
 
 Arguments:
 
-  NAME       Name of the environment variable.
-  VALUE      Value of the environment variable.
-"
+    NAME       Name of the environment variable.
+    VALUE      Value of the environment variable.
+" >&2
+    exit 1
+}
+
+die() {
+    echo "ERROR: $*" >&2
+    exit 1
 }
 
 valid_env_var_name() {
     case "$1" in
-        *[!A-Z0-9_]*|[0-9]*)
+        *[!A-Z0-9_]* | [0-9]*)
             return 1
             ;;
         *)
@@ -29,27 +43,19 @@ valid_env_var_name() {
 ENV_NAME="${1:-}"
 ENV_VAL="${2:-}"
 
-if [ "$ENV_NAME" = "-h" ] || [ "$ENV_NAME" = "--help" ]
-then
+if [ "${ENV_NAME}" = "-h" ] || [ "${ENV_NAME}" = "--help" ]; then
     usage
-    exit 1
 fi
 
-if [ -z "$ENV_NAME" ]
-then
-    echo "ERROR: Name of the environment variable missing."
-    echo ""
-    usage
-    exit 1
+if [ -z "${ENV_NAME}" ]; then
+    usage "Name of the environment variable missing."
 fi
 
-if ! valid_env_var_name "$ENV_NAME"
-then
-    echo "ERROR: Invalid environment variable name."
-    exit 1
+if ! valid_env_var_name "${ENV_NAME}"; then
+    die "Invalid environment variable name."
 fi
 
 # Write the environment variable.
-echo -n "$ENV_VAL" > /etc/cont-env.d/"$ENV_NAME"
+printf "%s" "${ENV_VAL}" > /etc/cont-env.d/"${ENV_NAME}"
 
 # vim:ft=sh:ts=4:sw=4:et:sts=4
diff --git a/helpers/take-ownership b/helpers/take-ownership
--- a/helpers/take-ownership
+++ b/helpers/take-ownership
@@ -42,6 +42,11 @@ set -e # Exit immediately if a command exits with a non-zero status.
 set -u # Treat unset variables as an error.
 
 usage() {
+    if [ -n "${1:-}" ]; then
+        echo "ERROR: $*" >&2
+        echo "" >&2
+    fi
+
     echo "usage: $(basename "$0") [OPTION...] TARGET
 
 Take ownership of the specified file/directory.
@@ -58,7 +63,13 @@ Options:
 
 Arguments:
   TARGET           Path to the file/directory to take ownership.
-"
+" >&2
+    exit 1
+}
+
+die() {
+    echo "ERROR: $*" >&2
+    exit 1
 }
 
 IGNORE_ERRORS=true
@@ -67,9 +78,8 @@ TARGET=
 
 while [ $# -gt 0 ]; do
     case "$1" in
-        --help|-h)
+        --help | -h)
             usage
-            exit 1
             ;;
         --not-recursive)
             RECURSIVE=false
@@ -81,8 +91,7 @@ while [ $# -gt 0 ]; do
             if [ -n "${2-}" ]; then
                 USER_ID="$2"
             else
-                echo "ERROR: User ID not set."
-                exit 1
+                usage "User ID not set."
             fi
             shift
             ;;
@@ -90,25 +99,18 @@ while [ $# -gt 0 ]; do
             if [ -n "${2-}" ]; then
                 GROUP_ID="$2"
             else
-                echo "ERROR: Group ID not set."
-                exit 1
+                usage "Group ID not set."
             fi
             shift
             ;;
         --*)
-            echo "ERROR: Unknown option '$1'."
-            echo ""
-            usage
-            exit 1
+            usage "Unknown option '$1'."
             ;;
         *)
             if [ -z "${TARGET:-}" ]; then
                 TARGET="$1"
             else
-                echo "ERROR: Unknown argument '$1'."
-                echo ""
-                usage
-                exit 1
+                usage "Unknown argument '$1'."
             fi
             ;;
     esac
@@ -118,50 +120,44 @@ done
 
 # Validate the target.
 if [ -z "${TARGET:-}" ]; then
-    echo "ERROR: Target not set."
-    echo ""
-    usage
-    exit 1
-elif [ ! -e "$TARGET" ]; then
-    echo "ERROR: Target not found: $TARGET."
-    exit 1
+    usage "Target not set."
+elif [ ! -e "${TARGET}" ]; then
+    die "Target not found: ${TARGET}."
 fi
 
 # Validate the user ID.
 if [ -z "${USER_ID:-}" ]; then
-    echo "ERROR: No user ID defined."
-    exit 1
+    die " No user ID defined."
 fi
 
 # Validate the group ID.
 if [ -z "${GROUP_ID:-}" ]; then
-    echo "ERROR: No group ID defined."
-    exit 1
+    die "No group ID defined."
 fi
 
 # Use absolute path.
-if [ -d "$TARGET" ]; then
-    TARGET="$(cd "$TARGET" && pwd)"
+if [ -d "${TARGET}" ]; then
+    TARGET="$(cd "${TARGET}" && pwd)"
 else
-    TARGET="$(cd "$(dirname "$TARGET")" && pwd)/$(basename "$TARGET")"
+    TARGET="$(cd "$(dirname "${TARGET}")" && pwd)/$(basename "${TARGET}")"
 fi
 
 # Create temporary file to store any chmod error.
-RES_FILE="$(mktemp)"
-echo "0" > "$RES_FILE"
+CHMOD_RES_FILE="$(mktemp)"
+echo "0" > "${CHMOD_RES_FILE}"
 
 # Create the chmod wrapper.
 CHOWN_WRAPPER="$(mktemp)"
 echo "#!/bin/sh
 chown \"\$@\"
-RES=\$?
-if [ \$RES -ne 0 ]; then
-    echo \$RES > \"$RES_FILE\"
-fi" > "$CHOWN_WRAPPER"
+rc=\$?
+if [ \$rc -ne 0 ]; then
+    echo \$rc > \"${CHMOD_RES_FILE}\"
+fi" > "${CHOWN_WRAPPER}"
 
 # Define extra find arguments needed when recursivity is disabled.
 FIND_EXTRA_ARGS=
-if ! $RECURSIVE; then
+if ! ${RECURSIVE}; then
     FIND_EXTRA_ARGS="-mindepth 0 -maxdepth 0"
 fi
 
@@ -169,25 +165,26 @@ fi
 # than a signed integer produces an error: instead of using the ID, use the
 # associated user/group name if it exists.
 # See https://savannah.gnu.org/bugs/index.php?64900
-USER_NAME="$(getent passwd "$USER_ID" | cut -d: -f1)"
+USER_NAME="$(getent passwd "${USER_ID}" | cut -d: -f1)"
 if [ -n "${USER_NAME:-}" ]; then
-    USER_ID="$USER_NAME"
+    USER_ID="${USER_NAME}"
 fi
-GROUP_NAME="$(getent group "$GROUP_ID" | cut -d: -f1)"
+GROUP_NAME="$(getent group "${GROUP_ID}" | cut -d: -f1)"
 if [ -n "${GROUP_NAME:-}" ]; then
-    GROUP_ID="$GROUP_NAME"
+    GROUP_ID="${GROUP_NAME}"
 fi
 
 # Set ownership on files and folders.
-find "$TARGET" $FIND_EXTRA_ARGS '(' -not -user "$USER_ID" -or -not -group "$GROUP_ID" ')' -exec /bin/sh "$CHOWN_WRAPPER" --no-dereference "$USER_ID:$GROUP_ID" {} +
+# shellcheck disable=2086
+find "${TARGET}" ${FIND_EXTRA_ARGS} '(' -not -user "${USER_ID}" -or -not -group "${GROUP_ID}" ')' -exec /bin/sh "${CHOWN_WRAPPER}" --no-dereference "${USER_ID}:${GROUP_ID}" {} +
 
 # Handle the result.
-RES="$(cat "$RES_FILE")"
-rm "$RES_FILE" "$CHOWN_WRAPPER"
-if $IGNORE_ERRORS; then
+result="$(cat "${CHMOD_RES_FILE}")"
+rm "${CHMOD_RES_FILE}" "${CHOWN_WRAPPER}"
+if ${IGNORE_ERRORS}; then
     exit 0
 else
-    exit "$RES"
+    exit "${result}"
 fi
 
 # vim:ft=sh:ts=4:sw=4:et:sts=4
diff --git a/rootfs/etc/services.d/exit b/rootfs/etc/services.d/exit
--- a/rootfs/etc/services.d/exit
+++ b/rootfs/etc/services.d/exit
@@ -1,5 +1,4 @@
 #!/bin/sh
-
 #
 # This is invoked by cinit when it exits.
 #
@@ -19,57 +18,27 @@ log() {
             echo "$*" | cut -c 4-
             ;;
         *)
-            printf "[%-${MIN_LOG_PREFIX_LENGTH}s] " "$STAGE"
+            printf "[%-${MIN_LOG_PREFIX_LENGTH}s] " "${STAGE}"
             echo "$*"
             ;;
     esac
 }
 
 log_script() {
-    while read OUTPUT; do
-        log "$1: $OUTPUT"
+    while IFS= read -r output; do
+        case "${output}" in
+            :::*) log "${output}" ;;
+            *) log "$1: ${output}" ;;
+        esac
     done
 }
 
 set_min_log_prefix_length() {
-    find /etc/services.d -maxdepth 1 -type d | while read DIR
-    do
-        if [ "${#DIR}" -gt "$MIN_LOG_PREFIX_LENGTH" ]; then
-            MIN_LOG_PREFIX_LENGTH="${#DIR}"
+    find /etc/services.d -maxdepth 1 -type d | while read -r dir; do
+        if [ "${#dir}" -gt "${MIN_LOG_PREFIX_LENGTH}" ]; then
+            MIN_LOG_PREFIX_LENGTH="${#dir}"
         fi
     done
-}
-
-# http://cfajohnson.com/shell/cus-faq-2.html#Q11
-run() {
-    j=1
-    while eval "\${pipestatus_$j+:} false"; do
-        unset pipestatus_$j
-        j=$(($j+1))
-    done
-    j=1 com= k=1 l=
-    for a; do
-        if [ "x$a" = 'x|' ]; then
-            com="$com { $l "'3>&-
-                          echo "pipestatus_'$j'=$?" >&3
-                      } 4>&- |'
-            j=$(($j+1)) l=
-        else
-            l="$l \"\$$k\""
-        fi
-        k=$(($k+1))
-    done
-    com="$com $l"' 3>&- >&4 4>&-
-        echo "pipestatus_'$j'=$?"'
-    exec 4>&1
-    eval "$(exec 3>&1; eval "$com")"
-    exec 4>&-
-    j=1
-    while eval "\${pipestatus_$j+:} false"; do
-        eval "[ \$pipestatus_$j -eq 0 ] || return \$pipestatus_$j"
-        j=$(($j+1))
-    done
-    return 0
 }
 
 set_min_log_prefix_length
@@ -77,30 +46,33 @@ set_min_log_prefix_length
 # Invoke finish scripts.
 log "executing container finish scripts..."
 if [ -d /etc/cont-finish.d ]; then
-    find /etc/cont-finish.d -maxdepth 1 -type f | sort | while read FILE
-    do
-        FILENAME="$(basename "$FILE")"
+    find /etc/cont-finish.d -maxdepth 1 -type f | sort | while read -r fpath; do
+        fname="$(basename "${fpath}")"
 
-        if [ ! -x "$FILE" ]; then
-            echo "WARNING: not executable, ignoring." | log_script "$FILENAME"
+        if [ ! -x "${fpath}" ]; then
+            echo "WARNING: not executable, ignoring." | log_script "${fname}"
             continue
         fi
-        echo "executing..." | log_script "$FILENAME"
+        echo "executing..." | log_script "${fname}"
 
-        set +e
-        run "$FILE" \| log_script "$FILENAME"
-        RC=$?
-        set -e
+        rc_file="$(mktemp)"
+        (
+            set +e
+            ${fpath}
+            echo $? > "${rc_file}"
+        ) | log_script "${fname}"
+        read -r rc < "${rc_file}"
+        rm -f "${rc_file}"
 
-        if [ $RC -eq 0 ]; then
-            echo "terminated successfully." | log_script "$FILENAME"
+        if [ "${rc}" -eq 0 ]; then
+            echo "terminated successfully." | log_script "${fname}"
         else
-            echo "terminated with error $RC." | log_script "$FILENAME"
+            echo "terminated with error ${rc}." | log_script "${fname}"
         fi
     done
 fi
 log "all container finish scripts executed."
 
-exit $EXIT_CODE
+exit "${EXIT_CODE}"
 
 # vim:ft=sh:ts=4:sw=4:et:sts=4
